"""DEVATTECH-30/35 transactions + audit log

Revision ID: 266e7be163e5
Revises: 00ec1be9d686
Create Date: 2026-07-01 21:40:57.887087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '266e7be163e5'
down_revision: Union[str, Sequence[str], None] = '00ec1be9d686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'LBP', 'USDT', name='transactioncurrency'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fraud_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'flagged', 'reversed', name='transactionstatus'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_transactions_receiver_id'), 'transactions', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_id'), 'transactions', ['sender_id'], unique=False)
    op.create_table('transaction_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_audit_logs_actor_id'), 'transaction_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_logs_id'), 'transaction_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_audit_logs_transaction_id'), 'transaction_audit_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_audit_logs_transaction_id'), table_name='transaction_audit_logs')
    op.drop_index(op.f('ix_transaction_audit_logs_id'), table_name='transaction_audit_logs')
    op.drop_index(op.f('ix_transaction_audit_logs_actor_id'), table_name='transaction_audit_logs')
    op.drop_table('transaction_audit_logs')
    op.drop_index(op.f('ix_transactions_sender_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
