"""define wallets schema

Revision ID: b7e555d21624
Revises: 
Create Date: 2026-06-27 17:21:04.397369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e555d21624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create the new enum type
    op.execute("CREATE TYPE currencyenum AS ENUM ('USD', 'LBP', 'USDT')")

    # Alter wallets currency column to use new enum
    op.execute("ALTER TABLE wallets ALTER COLUMN currency TYPE currencyenum USING currency::text::currencyenum")

    # Drop old enum type
    op.execute("DROP TYPE IF EXISTS walletcurrency")

    # Fix balance column
    op.alter_column('wallets', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))

    # Fix updated_at
    op.alter_column('wallets', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # Add unique constraint
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.create_unique_constraint('uq_wallet_user_currency', 'wallets', ['user_id', 'currency'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wallet_user_currency', 'wallets', type_='unique')
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.alter_column('wallets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wallets', 'balance',
               existing_type=sa.Numeric(precision=18, scale=4),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('wallets', 'currency',
               existing_type=sa.Enum('USD', 'LBP', 'USDT', name='currencyenum'),
               type_=postgresql.ENUM('USD', 'LBP', 'USDT', name='walletcurrency'),
               existing_nullable=False)
    op.add_column('users', sa.Column('role', postgresql.ENUM('customer', 'compliance_officer', 'admin', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'kyc_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'flagged', 'rejected', name='kycstatus'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('target_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey')),
    sa.UniqueConstraint('base_currency', 'target_currency', name=op.f('uq_exchange_rate_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_rates_target_currency'), 'exchange_rates', ['target_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selfie_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'flagged', 'rejected', name='kycrecordstatus'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kyc_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_records_pkey'))
    )
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_kyc_records_id'), 'kyc_records', ['id'], unique=False)
    # ### end Alembic commands ###
