"""add account number and iban to wallets

Revision ID: c2865623e38a
Revises: b7e555d21624
Create Date: 2026-06-27 18:27:56.779484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2865623e38a'
down_revision: Union[str, Sequence[str], None] = 'b7e555d21624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_records_id'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_user_id'), table_name='kyc_records')
    op.drop_table('kyc_records')
    op.drop_index(op.f('ix_exchange_rates_base_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_target_currency'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'kyc_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'flagged', 'rejected', name='kycstatus'),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'role')
    op.add_column('wallets', sa.Column('account_number', sa.String(length=16), nullable=True))
    op.add_column('wallets', sa.Column('iban', sa.String(length=34), nullable=True))
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'wallets', ['iban'])
    op.create_unique_constraint(None, 'wallets', ['account_number'])
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_constraint(None, 'wallets', type_='unique')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_column('wallets', 'iban')
    op.drop_column('wallets', 'account_number')
    op.add_column('users', sa.Column('role', postgresql.ENUM('customer', 'compliance_officer', 'admin', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'kyc_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'flagged', 'rejected', name='kycstatus'),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('target_currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey')),
    sa.UniqueConstraint('base_currency', 'target_currency', name=op.f('uq_exchange_rate_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_rates_target_currency'), 'exchange_rates', ['target_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_base_currency'), 'exchange_rates', ['base_currency'], unique=False)
    op.create_table('kyc_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selfie_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('id_photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'flagged', 'rejected', name='kycrecordstatus'), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('kyc_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('kyc_records_pkey'))
    )
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_kyc_records_id'), 'kyc_records', ['id'], unique=False)
    # ### end Alembic commands ###
