"""add account number and iban to wallets

Revision ID: deccd21785fd
Revises: c2865623e38a
Create Date: 2026-06-27 18:35:45.710991

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'deccd21785fd'
down_revision: Union[str, Sequence[str], None] = 'c2865623e38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
